import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header"
import Headermobile from "@/components/header-mobile"
import SideNav from "@/components/side-nav";
import PageWrapper from "@/components/page-wrapper";
import MarginWidthWrapper from "@/components/margin-width-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="flex">
          <SideNav/>
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header/>
              <Headermobile/>
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
